import type { Metadata } from "next";
import Link from "next/link";
import { LEGAL } from "@/lib/legal/company";
import { Clause, Highlight, LegalPage, List } from "@/components/legal/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service | AI Patent Register",
  description:
    "You own your invention and you own your report. What this service is, what it is not, and how we handle what you submit.",
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      intro="The short version: you own your invention, you own the report we produce for you, and we claim nothing. The rest of this page explains what the service is, what it is not, and what we do with what you send us."
    >
      <Clause n={1} title="Who we are">
        <p>
          {LEGAL.brand} is operated by {LEGAL.entity}, a company registered in Australia.
          These terms apply whenever you use the website or submit an idea for evaluation.
        </p>
        <p>
          You can reach us at{" "}
          <a className="text-ink underline underline-offset-2" href={`mailto:${LEGAL.contactEmail}`}>
            {LEGAL.contactEmail}
          </a>
          .
        </p>
      </Clause>

      <Clause n={2} title="What this service is, and what it is not">
        <p>
          We produce an automated, AI-generated assessment of an invention idea, plus a
          timestamped certificate recording that you submitted it to us on a given date. It
          is designed to help you decide whether talking to a patent attorney is worth your
          time and money.
        </p>
        <Highlight>
          <p className="font-medium">This service is not legal advice.</p>
          <p className="mt-2">
            We are not a law firm. We are not registered patent attorneys, and we do not
            employ any. Nothing we produce is a legal opinion on whether your invention is
            patentable, valid, or infringing, and nothing we produce should be relied on in
            place of advice from a registered patent attorney.
          </p>
        </Highlight>
        <p>Specifically, we do not:</p>
        <List
          items={[
            "File patent applications, or act for you before IP Australia or any patent office",
            "Draft patent specifications, claims, or any document for use in a patent application",
            "Conduct a professional prior-art search. Any comparable patents mentioned in your report are illustrative leads generated by an AI model, are unverified, and may not exist",
            "Give advice on the validity or infringement of any patent",
          ]}
        />
        <p>
          Our certificate records that you submitted an idea to us on a date. It is a private
          business record.{" "}
          <span className="text-ink">
            It is not a patent, not a patent application, and does not create a priority date
            or any legal right in your invention.
          </span>{" "}
          Australia and most other countries award patents to the first person to file an
          application, so only filing an application with a patent office secures your place
          in the queue.
        </p>
      </Clause>

      <Clause n={3} title="Ownership: your invention and your report">
        <Highlight>
          <p className="font-medium">You own your invention. You own your report.</p>
          <p className="mt-2">
            We claim no ownership of anything you submit, and we give you everything we
            produce for you. There is nothing here we hold back.
          </p>
        </Highlight>
        <p>
          <span className="text-ink">3.1 Your invention stays yours.</span> You keep all
          intellectual property rights in the idea, invention, and information you submit,
          including copyright in what you write. Submitting an idea to us transfers nothing
          and gives us no ownership interest of any kind.
        </p>
        <p>
          <span className="text-ink">3.2 Your report is yours.</span> To the extent that we
          hold any rights in the report and certificate we produce for you, we assign those
          rights to you. Where an assignment is not legally possible, we grant you a
          perpetual, worldwide, irrevocable, royalty-free licence to use, copy, and share
          them for any purpose. You may give them to a patent attorney, an investor, or
          anyone else, without asking us and without attribution.
        </p>
        <p>
          <span className="text-ink">3.3 What we are allowed to do.</span> You give us
          permission to process your submission for one purpose only: producing your report
          and certificate, and storing them so you can access them again later. That
          permission ends when your submission is deleted.
        </p>
        <p>
          <span className="text-ink">3.4 We will not use your idea.</span> We do not use
          submitted inventions to develop our own products or services, we do not disclose
          them to anyone else for their benefit, and we will not file a patent application
          on an idea submitted to us.
        </p>
        <p>
          <span className="text-ink">3.5 Anonymous comparison against other submissions.</span>{" "}
          To tell you whether anything similar has come through this service before, we
          compare the text of your submission against earlier submissions inside our own
          database. This comparison is automated and returns only counts. No submission text
          is ever shown to another user, no other submitter is identified to you, and you are
          never identified to them.
        </p>
      </Clause>

      <Clause n={4} title="Confidentiality">
        <p>
          Your submission is confidential. We do not sell it, publish it, or disclose it to
          anyone except as described in this clause and in our{" "}
          <Link className="text-ink underline underline-offset-2" href="/privacy">
            Privacy Policy
          </Link>
          .
        </p>
        <p>
          To produce your report we send the invention text to an AI provider,{" "}
          {LEGAL.aiProvider}, under a commercial agreement that:
        </p>
        <List
          items={[
            <>
              <span className="text-ink">Prohibits training.</span> The provider is
              contractually forbidden from using submissions or responses to train or
              fine-tune any AI model.
            </>,
            <>
              <span className="text-ink">Treats submissions as confidential.</span> What we
              send and what comes back are defined as our confidential information under that
              agreement.
            </>,
            <>
              <span className="text-ink">Leaves rights with us.</span> The provider acquires
              no intellectual property rights in anything sent or returned.
            </>,
          ]}
        />
        <p>
          We send only the title, industry, problem statement, and invention description.{" "}
          <span className="text-ink">
            We do not send your name, email address, or phone number to the AI provider.
          </span>
        </p>
        <p>
          Disclosure to a service provider bound by an obligation of confidence is generally
          not treated as making an invention publicly available, and so should not affect
          novelty. We cannot guarantee that outcome in every country, and if the timing of
          public disclosure matters to you, raise it with a patent attorney before you
          publish, sell, or demonstrate your invention anywhere.
        </p>
        <p>
          One honest limit: no provider&apos;s confidentiality commitment overrides the law.
          We and our providers may be required to disclose or retain information to comply
          with a court order or other legal obligation.
        </p>
      </Clause>

      <Clause n={5} title="Accuracy and limits of the assessment">
        <p>
          Scores, rankings, and written analysis are generated by an AI model. They are
          estimates. They can be wrong, incomplete, or inconsistent, and two similar
          submissions may receive different results.
        </p>
        <p>
          A favourable score does not mean your invention is patentable. An unfavourable score
          does not mean it is not. Only a registered patent attorney, working from a real
          prior-art search, can tell you that.
        </p>
        <p>
          The quality of your report depends on what you tell us. We assess only what your
          submission describes.
        </p>
      </Clause>

      <Clause n={6} title="Payment and refunds">
        <p>
          The fee is charged once per submission, at the price shown at checkout. Payment is
          processed by Stripe; we do not store your card details.
        </p>
        <p>
          If we fail to deliver your report, we refund you in full. Because the report is
          generated immediately after payment and cannot be returned once delivered, we do
          not otherwise offer refunds for a change of mind.
        </p>
        <p>
          Nothing in these terms excludes, restricts, or modifies any guarantee, right, or
          remedy you have under the Australian Consumer Law that cannot lawfully be excluded.
        </p>
      </Clause>

      <Clause n={7} title="Your responsibilities">
        <List
          items={[
            "Submit only inventions you are entitled to submit. Do not submit someone else's confidential information, or information you are under an obligation not to disclose.",
            "Keep your account credentials secure.",
            "Do not attempt to disrupt the service, or use it to generate unlawful content.",
          ]}
        />
      </Clause>

      <Clause n={8} title="Liability">
        <p>
          To the extent permitted by law, and subject to clause 6, our total liability arising
          out of or in connection with the service is limited to the amount you paid us for
          the submission the claim relates to.
        </p>
        <p>
          We are not liable for decisions you make on the basis of a report, including a
          decision to file or not to file a patent application, or for any loss of patent
          rights arising from your own public disclosure of your invention.
        </p>
      </Clause>

      <Clause n={9} title="Changes and governing law">
        <p>
          We may update these terms. The version in force is the one published here on the day
          you submit. Material changes will be reflected in the &ldquo;last updated&rdquo; date
          above.
        </p>
        <p>
          These terms are governed by the laws of {LEGAL.state}, Australia, and you and we
          submit to the non-exclusive jurisdiction of the courts of that place.
        </p>
      </Clause>
    </LegalPage>
  );
}
